
name: SonarQube Analysis

on:
  push:
    branches:
      - master

jobs:
  sonar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-profile-settings/frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install


      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=CaoimhinHawk1_CS4227-thinktank \
            -Dsonar.organization=caoimhinhawk1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.java.binaries=target
